from __future__ import annotations

from typing import Protocol


class ConversationModel(Protocol):
    """The language component used by SHION, not SHION as a whole."""

    def status(self) -> dict: ...
    def generate(self, session_id: str, mode: str, history: list[dict], message: str,
                 memory_context: str = "") -> tuple[str, dict]: ...
    def cancel(self, session_id: str) -> bool: ...
    def reset(self, session_id: str) -> None: ...
    def close(self) -> None: ...
